//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.08 at 11:15:13 PM PST 
//


package tcss556.services.models.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginResponse.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoginResponse"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SUCCEED"/&gt;
 *     &lt;enumeration value="BAD_PASSWORD"/&gt;
 *     &lt;enumeration value="NOT FOUND"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LoginResponse")
@XmlEnum
public enum LoginResponse {

    SUCCEED("SUCCEED"),
    BAD_PASSWORD("BAD_PASSWORD"),
    @XmlEnumValue("NOT FOUND")
    NOT_FOUND("NOT FOUND");
    private final String value;

    LoginResponse(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoginResponse fromValue(String v) {
        for (LoginResponse c: LoginResponse.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
