//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 01:49:10 AM PST 
//


package tcss556.services.models.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoginStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SUCCEED"/&gt;
 *     &lt;enumeration value="BAD_PASSWORD"/&gt;
 *     &lt;enumeration value="NOT FOUND"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LoginStatus")
@XmlEnum
public enum LoginStatus {

    SUCCEED("SUCCEED"),
    BAD_PASSWORD("BAD_PASSWORD"),
    @XmlEnumValue("NOT FOUND")
    NOT_FOUND("NOT FOUND");
    private final String value;

    LoginStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoginStatus fromValue(String v) {
        for (LoginStatus c: LoginStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
